# Generated by Django 4.2.5 on 2023-09-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WineQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_color', models.CharField(db_column='wine color', max_length=100)),
                ('fixed_acidity', models.DecimalField(blank=True, db_column='fixed acidity', decimal_places=65535, max_digits=65535, null=True)),
                ('volatile_acidity', models.DecimalField(blank=True, db_column='volatile acidity', decimal_places=65535, max_digits=65535, null=True)),
                ('citric_acid', models.DecimalField(blank=True, db_column='citric acid', decimal_places=65535, max_digits=65535, null=True)),
                ('residual_sugar', models.DecimalField(blank=True, db_column='residual sugar', decimal_places=65535, max_digits=65535, null=True)),
                ('chlorides', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('free_sulfur_dioxide', models.DecimalField(blank=True, db_column='free sulfur dioxide', decimal_places=65535, max_digits=65535, null=True)),
                ('total_sulfur_dioxide', models.DecimalField(blank=True, db_column='total sulfur dioxide', decimal_places=65535, max_digits=65535, null=True)),
                ('density', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('ph', models.DecimalField(blank=True, db_column='pH', decimal_places=65535, max_digits=65535, null=True)),
                ('sulphates', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('alcohol', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('quality', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wine quality',
                'managed': False,
            },
        ),
    ]
